/* freesmartphone-context.c generated by valac 0.16.0, the Vala compiler
 * generated from freesmartphone-context.vala, do not modify */

/* Generated by vala-dbus-binding-tool 0.4.0. Do not modify! */
/* Generated with: vala-dbus-binding-tool --api-path=/usr/local/share/freesmartphone/xml --directory=../src --strip-namespace=org --rename-namespace=freedesktop:FreeDesktop --rename-namespace=freesmartphone:FreeSmartphone --gdbus */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT (free_smartphone_context_client_get_type ())
#define FREE_SMARTPHONE_CONTEXT_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT, FreeSmartphoneContextClient))
#define FREE_SMARTPHONE_CONTEXT_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT))
#define FREE_SMARTPHONE_CONTEXT_CLIENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT, FreeSmartphoneContextClientIface))

typedef struct _FreeSmartphoneContextClient FreeSmartphoneContextClient;
typedef struct _FreeSmartphoneContextClientIface FreeSmartphoneContextClientIface;

#define FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT_PROXY (free_smartphone_context_client_proxy_get_type ())
typedef GDBusProxy FreeSmartphoneContextClientProxy;
typedef GDBusProxyClass FreeSmartphoneContextClientProxyClass;
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))

#define FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT_SYNC (free_smartphone_context_client_sync_get_type ())
#define FREE_SMARTPHONE_CONTEXT_CLIENT_SYNC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT_SYNC, FreeSmartphoneContextClientSync))
#define FREE_SMARTPHONE_CONTEXT_IS_CLIENT_SYNC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT_SYNC))
#define FREE_SMARTPHONE_CONTEXT_CLIENT_SYNC_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT_SYNC, FreeSmartphoneContextClientSyncIface))

typedef struct _FreeSmartphoneContextClientSync FreeSmartphoneContextClientSync;
typedef struct _FreeSmartphoneContextClientSyncIface FreeSmartphoneContextClientSyncIface;

#define FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT_SYNC_PROXY (free_smartphone_context_client_sync_proxy_get_type ())
typedef GDBusProxy FreeSmartphoneContextClientSyncProxy;
typedef GDBusProxyClass FreeSmartphoneContextClientSyncProxyClass;

#define FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER (free_smartphone_context_manager_get_type ())
#define FREE_SMARTPHONE_CONTEXT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER, FreeSmartphoneContextManager))
#define FREE_SMARTPHONE_CONTEXT_IS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER))
#define FREE_SMARTPHONE_CONTEXT_MANAGER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER, FreeSmartphoneContextManagerIface))

typedef struct _FreeSmartphoneContextManager FreeSmartphoneContextManager;
typedef struct _FreeSmartphoneContextManagerIface FreeSmartphoneContextManagerIface;

#define FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER_PROXY (free_smartphone_context_manager_proxy_get_type ())

#define FREE_SMARTPHONE_CONTEXT_TYPE_LOCATION_UPDATE_ACCURACY (free_smartphone_context_location_update_accuracy_get_type ())
typedef GDBusProxy FreeSmartphoneContextManagerProxy;
typedef GDBusProxyClass FreeSmartphoneContextManagerProxyClass;

#define FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER_SYNC (free_smartphone_context_manager_sync_get_type ())
#define FREE_SMARTPHONE_CONTEXT_MANAGER_SYNC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER_SYNC, FreeSmartphoneContextManagerSync))
#define FREE_SMARTPHONE_CONTEXT_IS_MANAGER_SYNC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER_SYNC))
#define FREE_SMARTPHONE_CONTEXT_MANAGER_SYNC_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER_SYNC, FreeSmartphoneContextManagerSyncIface))

typedef struct _FreeSmartphoneContextManagerSync FreeSmartphoneContextManagerSync;
typedef struct _FreeSmartphoneContextManagerSyncIface FreeSmartphoneContextManagerSyncIface;

#define FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER_SYNC_PROXY (free_smartphone_context_manager_sync_proxy_get_type ())
typedef GDBusProxy FreeSmartphoneContextManagerSyncProxy;
typedef GDBusProxyClass FreeSmartphoneContextManagerSyncProxyClass;

typedef enum  {
	FREE_SMARTPHONE_ERROR_INVALID_PARAMETER,
	FREE_SMARTPHONE_ERROR_INTERNAL_ERROR,
	FREE_SMARTPHONE_ERROR_SYSTEM_ERROR,
	FREE_SMARTPHONE_ERROR_UNSUPPORTED,
	FREE_SMARTPHONE_ERROR_UNAVAILABLE
} FreeSmartphoneError;
#define FREE_SMARTPHONE_ERROR free_smartphone_error_quark ()
struct _FreeSmartphoneContextClientIface {
	GTypeInterface parent_iface;
	void (*location_update) (FreeSmartphoneContextClient* self, GHashTable* from, GHashTable* to, GError** error);
};

struct _FreeSmartphoneContextClientSyncIface {
	GTypeInterface parent_iface;
	void (*location_update) (FreeSmartphoneContextClientSync* self, GHashTable* from, GHashTable* to, GError** error);
};

typedef enum  {
	FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_INVALID,
	FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_NAVI,
	FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_BEST,
	FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_10M,
	FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100M,
	FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_1KM,
	FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_3KM,
	FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100KM
} FreeSmartphoneContextLocationUpdateAccuracy;

struct _FreeSmartphoneContextManagerIface {
	GTypeInterface parent_iface;
	void (*subscribe_location_updates) (FreeSmartphoneContextManager* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*subscribe_location_updates_finish) (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error);
	void (*unsubscribe_location_updates) (FreeSmartphoneContextManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*unsubscribe_location_updates_finish) (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error);
};

struct _FreeSmartphoneContextManagerSyncIface {
	GTypeInterface parent_iface;
	void (*subscribe_location_updates) (FreeSmartphoneContextManagerSync* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GError** error);
	void (*unsubscribe_location_updates) (FreeSmartphoneContextManagerSync* self, GError** error);
};



GType free_smartphone_context_client_proxy_get_type (void) G_GNUC_CONST;
guint free_smartphone_context_client_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GQuark free_smartphone_error_quark (void);
GType free_smartphone_context_client_get_type (void) G_GNUC_CONST;
void free_smartphone_context_client_location_update (FreeSmartphoneContextClient* self, GHashTable* from, GHashTable* to, GError** error);
static void free_smartphone_context_client_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void free_smartphone_context_client_proxy_location_update (FreeSmartphoneContextClient* self, GHashTable* from, GHashTable* to, GError** error);
static void free_smartphone_context_client_proxy_free_smartphone_context_client_interface_init (FreeSmartphoneContextClientIface* iface);
static void _dbus_free_smartphone_context_client_location_update (FreeSmartphoneContextClient* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void free_smartphone_context_client_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* free_smartphone_context_client_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean free_smartphone_context_client_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _free_smartphone_context_client_unregister_object (gpointer user_data);
GType free_smartphone_context_client_sync_proxy_get_type (void) G_GNUC_CONST;
guint free_smartphone_context_client_sync_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType free_smartphone_context_client_sync_get_type (void) G_GNUC_CONST;
void free_smartphone_context_client_sync_location_update (FreeSmartphoneContextClientSync* self, GHashTable* from, GHashTable* to, GError** error);
static void free_smartphone_context_client_sync_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void free_smartphone_context_client_sync_proxy_location_update (FreeSmartphoneContextClientSync* self, GHashTable* from, GHashTable* to, GError** error);
static void free_smartphone_context_client_sync_proxy_free_smartphone_context_client_sync_interface_init (FreeSmartphoneContextClientSyncIface* iface);
static void _dbus_free_smartphone_context_client_sync_location_update (FreeSmartphoneContextClientSync* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void free_smartphone_context_client_sync_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* free_smartphone_context_client_sync_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean free_smartphone_context_client_sync_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _free_smartphone_context_client_sync_unregister_object (gpointer user_data);
GType free_smartphone_context_manager_proxy_get_type (void) G_GNUC_CONST;
guint free_smartphone_context_manager_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType free_smartphone_context_location_update_accuracy_get_type (void) G_GNUC_CONST;
FreeSmartphoneContextLocationUpdateAccuracy free_smartphone_context_location_update_accuracy_from_string (const char* str, GError** error);
const char* free_smartphone_context_location_update_accuracy_to_string (FreeSmartphoneContextLocationUpdateAccuracy value);
GType free_smartphone_context_manager_get_type (void) G_GNUC_CONST;
void free_smartphone_context_manager_subscribe_location_updates (FreeSmartphoneContextManager* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GAsyncReadyCallback _callback_, gpointer _user_data_);
void free_smartphone_context_manager_subscribe_location_updates_finish (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error);
void free_smartphone_context_manager_unsubscribe_location_updates (FreeSmartphoneContextManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void free_smartphone_context_manager_unsubscribe_location_updates_finish (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error);
static void free_smartphone_context_manager_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void _vala_g_async_ready_callback (GObject *source_object, GAsyncResult *res, void *user_data);
static void free_smartphone_context_manager_proxy_subscribe_location_updates_async (FreeSmartphoneContextManager* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void free_smartphone_context_manager_proxy_subscribe_location_updates_finish (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error);
static void free_smartphone_context_manager_proxy_unsubscribe_location_updates_async (FreeSmartphoneContextManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void free_smartphone_context_manager_proxy_unsubscribe_location_updates_finish (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error);
static void free_smartphone_context_manager_proxy_free_smartphone_context_manager_interface_init (FreeSmartphoneContextManagerIface* iface);
static void _dbus_free_smartphone_context_manager_subscribe_location_updates (FreeSmartphoneContextManager* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_context_manager_subscribe_location_updates_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_);
static void _dbus_free_smartphone_context_manager_unsubscribe_location_updates (FreeSmartphoneContextManager* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_context_manager_unsubscribe_location_updates_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_);
static void free_smartphone_context_manager_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* free_smartphone_context_manager_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean free_smartphone_context_manager_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _free_smartphone_context_manager_unregister_object (gpointer user_data);
GType free_smartphone_context_manager_sync_proxy_get_type (void) G_GNUC_CONST;
guint free_smartphone_context_manager_sync_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType free_smartphone_context_manager_sync_get_type (void) G_GNUC_CONST;
void free_smartphone_context_manager_sync_subscribe_location_updates (FreeSmartphoneContextManagerSync* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GError** error);
void free_smartphone_context_manager_sync_unsubscribe_location_updates (FreeSmartphoneContextManagerSync* self, GError** error);
static void free_smartphone_context_manager_sync_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void free_smartphone_context_manager_sync_proxy_subscribe_location_updates (FreeSmartphoneContextManagerSync* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GError** error);
static void free_smartphone_context_manager_sync_proxy_unsubscribe_location_updates (FreeSmartphoneContextManagerSync* self, GError** error);
static void free_smartphone_context_manager_sync_proxy_free_smartphone_context_manager_sync_interface_init (FreeSmartphoneContextManagerSyncIface* iface);
static void _dbus_free_smartphone_context_manager_sync_subscribe_location_updates (FreeSmartphoneContextManagerSync* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_context_manager_sync_unsubscribe_location_updates (FreeSmartphoneContextManagerSync* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void free_smartphone_context_manager_sync_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* free_smartphone_context_manager_sync_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean free_smartphone_context_manager_sync_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _free_smartphone_context_manager_sync_unregister_object (gpointer user_data);

static const GDBusArgInfo _free_smartphone_context_client_dbus_arg_info_location_update_from = {-1, "from", "a{sv}"};
static const GDBusArgInfo _free_smartphone_context_client_dbus_arg_info_location_update_to = {-1, "to", "a{sv}"};
static const GDBusArgInfo * const _free_smartphone_context_client_dbus_arg_info_location_update_in[] = {&_free_smartphone_context_client_dbus_arg_info_location_update_from, &_free_smartphone_context_client_dbus_arg_info_location_update_to, NULL};
static const GDBusArgInfo * const _free_smartphone_context_client_dbus_arg_info_location_update_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_context_client_dbus_method_info_location_update = {-1, "LocationUpdate", (GDBusArgInfo **) (&_free_smartphone_context_client_dbus_arg_info_location_update_in), (GDBusArgInfo **) (&_free_smartphone_context_client_dbus_arg_info_location_update_out)};
static const GDBusMethodInfo * const _free_smartphone_context_client_dbus_method_info[] = {&_free_smartphone_context_client_dbus_method_info_location_update, NULL};
static const GDBusSignalInfo * const _free_smartphone_context_client_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _free_smartphone_context_client_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _free_smartphone_context_client_dbus_interface_info = {-1, "org.freesmartphone.Context.Client", (GDBusMethodInfo **) (&_free_smartphone_context_client_dbus_method_info), (GDBusSignalInfo **) (&_free_smartphone_context_client_dbus_signal_info), (GDBusPropertyInfo **) (&_free_smartphone_context_client_dbus_property_info)};
static const GDBusInterfaceVTable _free_smartphone_context_client_dbus_interface_vtable = {free_smartphone_context_client_dbus_interface_method_call, free_smartphone_context_client_dbus_interface_get_property, free_smartphone_context_client_dbus_interface_set_property};
static const GDBusArgInfo _free_smartphone_context_client_sync_dbus_arg_info_location_update_from = {-1, "from", "a{sv}"};
static const GDBusArgInfo _free_smartphone_context_client_sync_dbus_arg_info_location_update_to = {-1, "to", "a{sv}"};
static const GDBusArgInfo * const _free_smartphone_context_client_sync_dbus_arg_info_location_update_in[] = {&_free_smartphone_context_client_sync_dbus_arg_info_location_update_from, &_free_smartphone_context_client_sync_dbus_arg_info_location_update_to, NULL};
static const GDBusArgInfo * const _free_smartphone_context_client_sync_dbus_arg_info_location_update_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_context_client_sync_dbus_method_info_location_update = {-1, "LocationUpdate", (GDBusArgInfo **) (&_free_smartphone_context_client_sync_dbus_arg_info_location_update_in), (GDBusArgInfo **) (&_free_smartphone_context_client_sync_dbus_arg_info_location_update_out)};
static const GDBusMethodInfo * const _free_smartphone_context_client_sync_dbus_method_info[] = {&_free_smartphone_context_client_sync_dbus_method_info_location_update, NULL};
static const GDBusSignalInfo * const _free_smartphone_context_client_sync_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _free_smartphone_context_client_sync_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _free_smartphone_context_client_sync_dbus_interface_info = {-1, "org.freesmartphone.Context.Client", (GDBusMethodInfo **) (&_free_smartphone_context_client_sync_dbus_method_info), (GDBusSignalInfo **) (&_free_smartphone_context_client_sync_dbus_signal_info), (GDBusPropertyInfo **) (&_free_smartphone_context_client_sync_dbus_property_info)};
static const GDBusInterfaceVTable _free_smartphone_context_client_sync_dbus_interface_vtable = {free_smartphone_context_client_sync_dbus_interface_method_call, free_smartphone_context_client_sync_dbus_interface_get_property, free_smartphone_context_client_sync_dbus_interface_set_property};
static const GDBusArgInfo _free_smartphone_context_manager_dbus_arg_info_subscribe_location_updates_desired_accuracy = {-1, "desired_accuracy", "s"};
static const GDBusArgInfo * const _free_smartphone_context_manager_dbus_arg_info_subscribe_location_updates_in[] = {&_free_smartphone_context_manager_dbus_arg_info_subscribe_location_updates_desired_accuracy, NULL};
static const GDBusArgInfo * const _free_smartphone_context_manager_dbus_arg_info_subscribe_location_updates_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_context_manager_dbus_method_info_subscribe_location_updates = {-1, "SubscribeLocationUpdates", (GDBusArgInfo **) (&_free_smartphone_context_manager_dbus_arg_info_subscribe_location_updates_in), (GDBusArgInfo **) (&_free_smartphone_context_manager_dbus_arg_info_subscribe_location_updates_out)};
static const GDBusArgInfo * const _free_smartphone_context_manager_dbus_arg_info_unsubscribe_location_updates_in[] = {NULL};
static const GDBusArgInfo * const _free_smartphone_context_manager_dbus_arg_info_unsubscribe_location_updates_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_context_manager_dbus_method_info_unsubscribe_location_updates = {-1, "UnsubscribeLocationUpdates", (GDBusArgInfo **) (&_free_smartphone_context_manager_dbus_arg_info_unsubscribe_location_updates_in), (GDBusArgInfo **) (&_free_smartphone_context_manager_dbus_arg_info_unsubscribe_location_updates_out)};
static const GDBusMethodInfo * const _free_smartphone_context_manager_dbus_method_info[] = {&_free_smartphone_context_manager_dbus_method_info_subscribe_location_updates, &_free_smartphone_context_manager_dbus_method_info_unsubscribe_location_updates, NULL};
static const GDBusSignalInfo * const _free_smartphone_context_manager_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _free_smartphone_context_manager_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _free_smartphone_context_manager_dbus_interface_info = {-1, "org.freesmartphone.Context.Manager", (GDBusMethodInfo **) (&_free_smartphone_context_manager_dbus_method_info), (GDBusSignalInfo **) (&_free_smartphone_context_manager_dbus_signal_info), (GDBusPropertyInfo **) (&_free_smartphone_context_manager_dbus_property_info)};
static const GDBusInterfaceVTable _free_smartphone_context_manager_dbus_interface_vtable = {free_smartphone_context_manager_dbus_interface_method_call, free_smartphone_context_manager_dbus_interface_get_property, free_smartphone_context_manager_dbus_interface_set_property};
static const GDBusArgInfo _free_smartphone_context_manager_sync_dbus_arg_info_subscribe_location_updates_desired_accuracy = {-1, "desired_accuracy", "s"};
static const GDBusArgInfo * const _free_smartphone_context_manager_sync_dbus_arg_info_subscribe_location_updates_in[] = {&_free_smartphone_context_manager_sync_dbus_arg_info_subscribe_location_updates_desired_accuracy, NULL};
static const GDBusArgInfo * const _free_smartphone_context_manager_sync_dbus_arg_info_subscribe_location_updates_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_context_manager_sync_dbus_method_info_subscribe_location_updates = {-1, "SubscribeLocationUpdates", (GDBusArgInfo **) (&_free_smartphone_context_manager_sync_dbus_arg_info_subscribe_location_updates_in), (GDBusArgInfo **) (&_free_smartphone_context_manager_sync_dbus_arg_info_subscribe_location_updates_out)};
static const GDBusArgInfo * const _free_smartphone_context_manager_sync_dbus_arg_info_unsubscribe_location_updates_in[] = {NULL};
static const GDBusArgInfo * const _free_smartphone_context_manager_sync_dbus_arg_info_unsubscribe_location_updates_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_context_manager_sync_dbus_method_info_unsubscribe_location_updates = {-1, "UnsubscribeLocationUpdates", (GDBusArgInfo **) (&_free_smartphone_context_manager_sync_dbus_arg_info_unsubscribe_location_updates_in), (GDBusArgInfo **) (&_free_smartphone_context_manager_sync_dbus_arg_info_unsubscribe_location_updates_out)};
static const GDBusMethodInfo * const _free_smartphone_context_manager_sync_dbus_method_info[] = {&_free_smartphone_context_manager_sync_dbus_method_info_subscribe_location_updates, &_free_smartphone_context_manager_sync_dbus_method_info_unsubscribe_location_updates, NULL};
static const GDBusSignalInfo * const _free_smartphone_context_manager_sync_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _free_smartphone_context_manager_sync_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _free_smartphone_context_manager_sync_dbus_interface_info = {-1, "org.freesmartphone.Context.Manager", (GDBusMethodInfo **) (&_free_smartphone_context_manager_sync_dbus_method_info), (GDBusSignalInfo **) (&_free_smartphone_context_manager_sync_dbus_signal_info), (GDBusPropertyInfo **) (&_free_smartphone_context_manager_sync_dbus_property_info)};
static const GDBusInterfaceVTable _free_smartphone_context_manager_sync_dbus_interface_vtable = {free_smartphone_context_manager_sync_dbus_interface_method_call, free_smartphone_context_manager_sync_dbus_interface_get_property, free_smartphone_context_manager_sync_dbus_interface_set_property};

void free_smartphone_context_client_location_update (FreeSmartphoneContextClient* self, GHashTable* from, GHashTable* to, GError** error) {
	g_return_if_fail (self != NULL);
	FREE_SMARTPHONE_CONTEXT_CLIENT_GET_INTERFACE (self)->location_update (self, from, to, error);
}


static void free_smartphone_context_client_base_init (FreeSmartphoneContextClientIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType free_smartphone_context_client_get_type (void) {
	static volatile gsize free_smartphone_context_client_type_id__volatile = 0;
	if (g_once_init_enter (&free_smartphone_context_client_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FreeSmartphoneContextClientIface), (GBaseInitFunc) free_smartphone_context_client_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType free_smartphone_context_client_type_id;
		free_smartphone_context_client_type_id = g_type_register_static (G_TYPE_INTERFACE, "FreeSmartphoneContextClient", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (free_smartphone_context_client_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (free_smartphone_context_client_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) free_smartphone_context_client_proxy_get_type);
		g_type_set_qdata (free_smartphone_context_client_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freesmartphone.Context.Client");
		g_type_set_qdata (free_smartphone_context_client_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) free_smartphone_context_client_register_object);
		g_once_init_leave (&free_smartphone_context_client_type_id__volatile, free_smartphone_context_client_type_id);
	}
	return free_smartphone_context_client_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (FreeSmartphoneContextClientProxy, free_smartphone_context_client_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT, free_smartphone_context_client_proxy_free_smartphone_context_client_interface_init) )
static void free_smartphone_context_client_proxy_class_init (FreeSmartphoneContextClientProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = free_smartphone_context_client_proxy_g_signal;
}


static void free_smartphone_context_client_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void free_smartphone_context_client_proxy_init (FreeSmartphoneContextClientProxy* self) {
}


static void free_smartphone_context_client_proxy_location_update (FreeSmartphoneContextClient* self, GHashTable* from, GHashTable* to, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GVariantBuilder _tmp290_;
	GHashTableIter _tmp291_;
	gpointer _tmp292_;
	gpointer _tmp293_;
	GVariantBuilder _tmp294_;
	GHashTableIter _tmp295_;
	gpointer _tmp296_;
	gpointer _tmp297_;
	FREE_SMARTPHONE_ERROR;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Context.Client", "LocationUpdate");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_hash_table_iter_init (&_tmp291_, from);
	g_variant_builder_init (&_tmp290_, G_VARIANT_TYPE ("a{sv}"));
	while (g_hash_table_iter_next (&_tmp291_, &_tmp292_, &_tmp293_)) {
		gchar* _key;
		GVariant* _value;
		_key = (gchar*) _tmp292_;
		_value = (GVariant*) _tmp293_;
		g_variant_builder_add (&_tmp290_, "{?*}", g_variant_new_string (_key), g_variant_new_variant (_value));
	}
	g_variant_builder_add_value (&_arguments_builder, g_variant_builder_end (&_tmp290_));
	g_hash_table_iter_init (&_tmp295_, to);
	g_variant_builder_init (&_tmp294_, G_VARIANT_TYPE ("a{sv}"));
	while (g_hash_table_iter_next (&_tmp295_, &_tmp296_, &_tmp297_)) {
		gchar* _key;
		GVariant* _value;
		_key = (gchar*) _tmp296_;
		_value = (GVariant*) _tmp297_;
		g_variant_builder_add (&_tmp294_, "{?*}", g_variant_new_string (_key), g_variant_new_variant (_value));
	}
	g_variant_builder_add_value (&_arguments_builder, g_variant_builder_end (&_tmp294_));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	g_dbus_message_set_flags (_message, G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED);
	g_dbus_connection_send_message (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, error);
	g_object_unref (_message);
}


static void free_smartphone_context_client_proxy_free_smartphone_context_client_interface_init (FreeSmartphoneContextClientIface* iface) {
	iface->location_update = free_smartphone_context_client_proxy_location_update;
}


static void _dbus_free_smartphone_context_client_location_update (FreeSmartphoneContextClient* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GHashTable* from = NULL;
	GVariant* _tmp298_;
	GHashTable* _tmp299_;
	GVariantIter _tmp300_;
	GVariant* _tmp301_;
	GVariant* _tmp302_;
	GHashTable* to = NULL;
	GVariant* _tmp303_;
	GHashTable* _tmp304_;
	GVariantIter _tmp305_;
	GVariant* _tmp306_;
	GVariant* _tmp307_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp298_ = g_variant_iter_next_value (&_arguments_iter);
	_tmp299_ = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
	g_variant_iter_init (&_tmp300_, _tmp298_);
	while (g_variant_iter_loop (&_tmp300_, "{?*}", &_tmp301_, &_tmp302_)) {
		g_hash_table_insert (_tmp299_, g_variant_dup_string (_tmp301_, NULL), g_variant_get_variant (_tmp302_));
	}
	from = _tmp299_;
	g_variant_unref (_tmp298_);
	_tmp303_ = g_variant_iter_next_value (&_arguments_iter);
	_tmp304_ = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
	g_variant_iter_init (&_tmp305_, _tmp303_);
	while (g_variant_iter_loop (&_tmp305_, "{?*}", &_tmp306_, &_tmp307_)) {
		g_hash_table_insert (_tmp304_, g_variant_dup_string (_tmp306_, NULL), g_variant_get_variant (_tmp307_));
	}
	to = _tmp304_;
	g_variant_unref (_tmp303_);
	free_smartphone_context_client_location_update (self, from, to, &error);
	_g_hash_table_unref0 (from);
	_g_hash_table_unref0 (to);
}


static void free_smartphone_context_client_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "LocationUpdate") == 0) {
		_dbus_free_smartphone_context_client_location_update (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* free_smartphone_context_client_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean free_smartphone_context_client_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint free_smartphone_context_client_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_free_smartphone_context_client_dbus_interface_info), &_free_smartphone_context_client_dbus_interface_vtable, data, _free_smartphone_context_client_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _free_smartphone_context_client_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


void free_smartphone_context_client_sync_location_update (FreeSmartphoneContextClientSync* self, GHashTable* from, GHashTable* to, GError** error) {
	g_return_if_fail (self != NULL);
	FREE_SMARTPHONE_CONTEXT_CLIENT_SYNC_GET_INTERFACE (self)->location_update (self, from, to, error);
}


static void free_smartphone_context_client_sync_base_init (FreeSmartphoneContextClientSyncIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType free_smartphone_context_client_sync_get_type (void) {
	static volatile gsize free_smartphone_context_client_sync_type_id__volatile = 0;
	if (g_once_init_enter (&free_smartphone_context_client_sync_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FreeSmartphoneContextClientSyncIface), (GBaseInitFunc) free_smartphone_context_client_sync_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType free_smartphone_context_client_sync_type_id;
		free_smartphone_context_client_sync_type_id = g_type_register_static (G_TYPE_INTERFACE, "FreeSmartphoneContextClientSync", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (free_smartphone_context_client_sync_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (free_smartphone_context_client_sync_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) free_smartphone_context_client_sync_proxy_get_type);
		g_type_set_qdata (free_smartphone_context_client_sync_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freesmartphone.Context.Client");
		g_type_set_qdata (free_smartphone_context_client_sync_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) free_smartphone_context_client_sync_register_object);
		g_once_init_leave (&free_smartphone_context_client_sync_type_id__volatile, free_smartphone_context_client_sync_type_id);
	}
	return free_smartphone_context_client_sync_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (FreeSmartphoneContextClientSyncProxy, free_smartphone_context_client_sync_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (FREE_SMARTPHONE_CONTEXT_TYPE_CLIENT_SYNC, free_smartphone_context_client_sync_proxy_free_smartphone_context_client_sync_interface_init) )
static void free_smartphone_context_client_sync_proxy_class_init (FreeSmartphoneContextClientSyncProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = free_smartphone_context_client_sync_proxy_g_signal;
}


static void free_smartphone_context_client_sync_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void free_smartphone_context_client_sync_proxy_init (FreeSmartphoneContextClientSyncProxy* self) {
}


static void free_smartphone_context_client_sync_proxy_location_update (FreeSmartphoneContextClientSync* self, GHashTable* from, GHashTable* to, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GVariantBuilder _tmp308_;
	GHashTableIter _tmp309_;
	gpointer _tmp310_;
	gpointer _tmp311_;
	GVariantBuilder _tmp312_;
	GHashTableIter _tmp313_;
	gpointer _tmp314_;
	gpointer _tmp315_;
	FREE_SMARTPHONE_ERROR;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Context.Client", "LocationUpdate");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_hash_table_iter_init (&_tmp309_, from);
	g_variant_builder_init (&_tmp308_, G_VARIANT_TYPE ("a{sv}"));
	while (g_hash_table_iter_next (&_tmp309_, &_tmp310_, &_tmp311_)) {
		gchar* _key;
		GVariant* _value;
		_key = (gchar*) _tmp310_;
		_value = (GVariant*) _tmp311_;
		g_variant_builder_add (&_tmp308_, "{?*}", g_variant_new_string (_key), g_variant_new_variant (_value));
	}
	g_variant_builder_add_value (&_arguments_builder, g_variant_builder_end (&_tmp308_));
	g_hash_table_iter_init (&_tmp313_, to);
	g_variant_builder_init (&_tmp312_, G_VARIANT_TYPE ("a{sv}"));
	while (g_hash_table_iter_next (&_tmp313_, &_tmp314_, &_tmp315_)) {
		gchar* _key;
		GVariant* _value;
		_key = (gchar*) _tmp314_;
		_value = (GVariant*) _tmp315_;
		g_variant_builder_add (&_tmp312_, "{?*}", g_variant_new_string (_key), g_variant_new_variant (_value));
	}
	g_variant_builder_add_value (&_arguments_builder, g_variant_builder_end (&_tmp312_));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	g_dbus_message_set_flags (_message, G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED);
	g_dbus_connection_send_message (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, error);
	g_object_unref (_message);
}


static void free_smartphone_context_client_sync_proxy_free_smartphone_context_client_sync_interface_init (FreeSmartphoneContextClientSyncIface* iface) {
	iface->location_update = free_smartphone_context_client_sync_proxy_location_update;
}


static void _dbus_free_smartphone_context_client_sync_location_update (FreeSmartphoneContextClientSync* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GHashTable* from = NULL;
	GVariant* _tmp316_;
	GHashTable* _tmp317_;
	GVariantIter _tmp318_;
	GVariant* _tmp319_;
	GVariant* _tmp320_;
	GHashTable* to = NULL;
	GVariant* _tmp321_;
	GHashTable* _tmp322_;
	GVariantIter _tmp323_;
	GVariant* _tmp324_;
	GVariant* _tmp325_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp316_ = g_variant_iter_next_value (&_arguments_iter);
	_tmp317_ = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
	g_variant_iter_init (&_tmp318_, _tmp316_);
	while (g_variant_iter_loop (&_tmp318_, "{?*}", &_tmp319_, &_tmp320_)) {
		g_hash_table_insert (_tmp317_, g_variant_dup_string (_tmp319_, NULL), g_variant_get_variant (_tmp320_));
	}
	from = _tmp317_;
	g_variant_unref (_tmp316_);
	_tmp321_ = g_variant_iter_next_value (&_arguments_iter);
	_tmp322_ = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
	g_variant_iter_init (&_tmp323_, _tmp321_);
	while (g_variant_iter_loop (&_tmp323_, "{?*}", &_tmp324_, &_tmp325_)) {
		g_hash_table_insert (_tmp322_, g_variant_dup_string (_tmp324_, NULL), g_variant_get_variant (_tmp325_));
	}
	to = _tmp322_;
	g_variant_unref (_tmp321_);
	free_smartphone_context_client_sync_location_update (self, from, to, &error);
	_g_hash_table_unref0 (from);
	_g_hash_table_unref0 (to);
}


static void free_smartphone_context_client_sync_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "LocationUpdate") == 0) {
		_dbus_free_smartphone_context_client_sync_location_update (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* free_smartphone_context_client_sync_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean free_smartphone_context_client_sync_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint free_smartphone_context_client_sync_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_free_smartphone_context_client_sync_dbus_interface_info), &_free_smartphone_context_client_sync_dbus_interface_vtable, data, _free_smartphone_context_client_sync_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _free_smartphone_context_client_sync_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


void free_smartphone_context_manager_subscribe_location_updates (FreeSmartphoneContextManager* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FREE_SMARTPHONE_CONTEXT_MANAGER_GET_INTERFACE (self)->subscribe_location_updates (self, desired_accuracy, _callback_, _user_data_);
}


void free_smartphone_context_manager_subscribe_location_updates_finish (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error) {
	FREE_SMARTPHONE_CONTEXT_MANAGER_GET_INTERFACE (self)->subscribe_location_updates_finish (self, _res_, error);
}


void free_smartphone_context_manager_unsubscribe_location_updates (FreeSmartphoneContextManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FREE_SMARTPHONE_CONTEXT_MANAGER_GET_INTERFACE (self)->unsubscribe_location_updates (self, _callback_, _user_data_);
}


void free_smartphone_context_manager_unsubscribe_location_updates_finish (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error) {
	FREE_SMARTPHONE_CONTEXT_MANAGER_GET_INTERFACE (self)->unsubscribe_location_updates_finish (self, _res_, error);
}


static void free_smartphone_context_manager_base_init (FreeSmartphoneContextManagerIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType free_smartphone_context_manager_get_type (void) {
	static volatile gsize free_smartphone_context_manager_type_id__volatile = 0;
	if (g_once_init_enter (&free_smartphone_context_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FreeSmartphoneContextManagerIface), (GBaseInitFunc) free_smartphone_context_manager_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType free_smartphone_context_manager_type_id;
		free_smartphone_context_manager_type_id = g_type_register_static (G_TYPE_INTERFACE, "FreeSmartphoneContextManager", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (free_smartphone_context_manager_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (free_smartphone_context_manager_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) free_smartphone_context_manager_proxy_get_type);
		g_type_set_qdata (free_smartphone_context_manager_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freesmartphone.Context.Manager");
		g_type_set_qdata (free_smartphone_context_manager_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) free_smartphone_context_manager_register_object);
		g_once_init_leave (&free_smartphone_context_manager_type_id__volatile, free_smartphone_context_manager_type_id);
	}
	return free_smartphone_context_manager_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (FreeSmartphoneContextManagerProxy, free_smartphone_context_manager_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER, free_smartphone_context_manager_proxy_free_smartphone_context_manager_interface_init) )
static void free_smartphone_context_manager_proxy_class_init (FreeSmartphoneContextManagerProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = free_smartphone_context_manager_proxy_g_signal;
}


static void free_smartphone_context_manager_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void free_smartphone_context_manager_proxy_init (FreeSmartphoneContextManagerProxy* self) {
}


static void _vala_g_async_ready_callback (GObject *source_object, GAsyncResult *res, void *user_data) {
	g_simple_async_result_set_op_res_gpointer (user_data, g_object_ref (res), g_object_unref);
	g_simple_async_result_complete (user_data);
	g_object_unref (user_data);
}


static void free_smartphone_context_manager_proxy_subscribe_location_updates_async (FreeSmartphoneContextManager* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	FREE_SMARTPHONE_ERROR;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Context.Manager", "SubscribeLocationUpdates");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (free_smartphone_context_location_update_accuracy_to_string (desired_accuracy)));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	g_dbus_connection_send_message_with_reply (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, _vala_g_async_ready_callback, g_simple_async_result_new ((GObject *) self, _callback_, _user_data_, NULL));
	g_object_unref (_message);
}


static void free_smartphone_context_manager_proxy_subscribe_location_updates_finish (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error) {
	GDBusMessage *_reply_message;
	_reply_message = g_dbus_connection_send_message_with_reply_finish (g_dbus_proxy_get_connection ((GDBusProxy *) self), g_simple_async_result_get_op_res_gpointer ((GSimpleAsyncResult *) _res_), error);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_context_manager_proxy_unsubscribe_location_updates_async (FreeSmartphoneContextManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	FREE_SMARTPHONE_ERROR;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Context.Manager", "UnsubscribeLocationUpdates");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	g_dbus_connection_send_message_with_reply (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, _vala_g_async_ready_callback, g_simple_async_result_new ((GObject *) self, _callback_, _user_data_, NULL));
	g_object_unref (_message);
}


static void free_smartphone_context_manager_proxy_unsubscribe_location_updates_finish (FreeSmartphoneContextManager* self, GAsyncResult* _res_, GError** error) {
	GDBusMessage *_reply_message;
	_reply_message = g_dbus_connection_send_message_with_reply_finish (g_dbus_proxy_get_connection ((GDBusProxy *) self), g_simple_async_result_get_op_res_gpointer ((GSimpleAsyncResult *) _res_), error);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_context_manager_proxy_free_smartphone_context_manager_interface_init (FreeSmartphoneContextManagerIface* iface) {
	iface->subscribe_location_updates = free_smartphone_context_manager_proxy_subscribe_location_updates_async;
	iface->subscribe_location_updates_finish = free_smartphone_context_manager_proxy_subscribe_location_updates_finish;
	iface->unsubscribe_location_updates = free_smartphone_context_manager_proxy_unsubscribe_location_updates_async;
	iface->unsubscribe_location_updates_finish = free_smartphone_context_manager_proxy_unsubscribe_location_updates_finish;
}


static void _dbus_free_smartphone_context_manager_subscribe_location_updates (FreeSmartphoneContextManager* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GVariantIter _arguments_iter;
	FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy = 0;
	GVariant* _tmp326_;
	GError* error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp326_ = g_variant_iter_next_value (&_arguments_iter);
	desired_accuracy = free_smartphone_context_location_update_accuracy_from_string (g_variant_get_string (_tmp326_, NULL), &error);
	g_variant_unref (_tmp326_);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	free_smartphone_context_manager_subscribe_location_updates (self, desired_accuracy, (GAsyncReadyCallback) _dbus_free_smartphone_context_manager_subscribe_location_updates_ready, invocation);
}


static void _dbus_free_smartphone_context_manager_subscribe_location_updates_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_) {
	GDBusMethodInvocation * invocation;
	GError* error = NULL;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	invocation = _user_data_;
	free_smartphone_context_manager_subscribe_location_updates_finish ((FreeSmartphoneContextManager*) source_object, _res_, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_free_smartphone_context_manager_unsubscribe_location_updates (FreeSmartphoneContextManager* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GVariantIter _arguments_iter;
	g_variant_iter_init (&_arguments_iter, parameters);
	free_smartphone_context_manager_unsubscribe_location_updates (self, (GAsyncReadyCallback) _dbus_free_smartphone_context_manager_unsubscribe_location_updates_ready, invocation);
}


static void _dbus_free_smartphone_context_manager_unsubscribe_location_updates_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_) {
	GDBusMethodInvocation * invocation;
	GError* error = NULL;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	invocation = _user_data_;
	free_smartphone_context_manager_unsubscribe_location_updates_finish ((FreeSmartphoneContextManager*) source_object, _res_, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void free_smartphone_context_manager_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "SubscribeLocationUpdates") == 0) {
		_dbus_free_smartphone_context_manager_subscribe_location_updates (object, parameters, invocation);
	} else if (strcmp (method_name, "UnsubscribeLocationUpdates") == 0) {
		_dbus_free_smartphone_context_manager_unsubscribe_location_updates (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* free_smartphone_context_manager_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean free_smartphone_context_manager_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint free_smartphone_context_manager_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_free_smartphone_context_manager_dbus_interface_info), &_free_smartphone_context_manager_dbus_interface_vtable, data, _free_smartphone_context_manager_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _free_smartphone_context_manager_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


void free_smartphone_context_manager_sync_subscribe_location_updates (FreeSmartphoneContextManagerSync* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GError** error) {
	g_return_if_fail (self != NULL);
	FREE_SMARTPHONE_CONTEXT_MANAGER_SYNC_GET_INTERFACE (self)->subscribe_location_updates (self, desired_accuracy, error);
}


void free_smartphone_context_manager_sync_unsubscribe_location_updates (FreeSmartphoneContextManagerSync* self, GError** error) {
	g_return_if_fail (self != NULL);
	FREE_SMARTPHONE_CONTEXT_MANAGER_SYNC_GET_INTERFACE (self)->unsubscribe_location_updates (self, error);
}


static void free_smartphone_context_manager_sync_base_init (FreeSmartphoneContextManagerSyncIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType free_smartphone_context_manager_sync_get_type (void) {
	static volatile gsize free_smartphone_context_manager_sync_type_id__volatile = 0;
	if (g_once_init_enter (&free_smartphone_context_manager_sync_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FreeSmartphoneContextManagerSyncIface), (GBaseInitFunc) free_smartphone_context_manager_sync_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType free_smartphone_context_manager_sync_type_id;
		free_smartphone_context_manager_sync_type_id = g_type_register_static (G_TYPE_INTERFACE, "FreeSmartphoneContextManagerSync", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (free_smartphone_context_manager_sync_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (free_smartphone_context_manager_sync_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) free_smartphone_context_manager_sync_proxy_get_type);
		g_type_set_qdata (free_smartphone_context_manager_sync_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freesmartphone.Context.Manager");
		g_type_set_qdata (free_smartphone_context_manager_sync_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) free_smartphone_context_manager_sync_register_object);
		g_once_init_leave (&free_smartphone_context_manager_sync_type_id__volatile, free_smartphone_context_manager_sync_type_id);
	}
	return free_smartphone_context_manager_sync_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (FreeSmartphoneContextManagerSyncProxy, free_smartphone_context_manager_sync_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (FREE_SMARTPHONE_CONTEXT_TYPE_MANAGER_SYNC, free_smartphone_context_manager_sync_proxy_free_smartphone_context_manager_sync_interface_init) )
static void free_smartphone_context_manager_sync_proxy_class_init (FreeSmartphoneContextManagerSyncProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = free_smartphone_context_manager_sync_proxy_g_signal;
}


static void free_smartphone_context_manager_sync_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void free_smartphone_context_manager_sync_proxy_init (FreeSmartphoneContextManagerSyncProxy* self) {
}


static void free_smartphone_context_manager_sync_proxy_subscribe_location_updates (FreeSmartphoneContextManagerSync* self, FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	FREE_SMARTPHONE_ERROR;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Context.Manager", "SubscribeLocationUpdates");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (free_smartphone_context_location_update_accuracy_to_string (desired_accuracy)));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_context_manager_sync_proxy_unsubscribe_location_updates (FreeSmartphoneContextManagerSync* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	FREE_SMARTPHONE_ERROR;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Context.Manager", "UnsubscribeLocationUpdates");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_context_manager_sync_proxy_free_smartphone_context_manager_sync_interface_init (FreeSmartphoneContextManagerSyncIface* iface) {
	iface->subscribe_location_updates = free_smartphone_context_manager_sync_proxy_subscribe_location_updates;
	iface->unsubscribe_location_updates = free_smartphone_context_manager_sync_proxy_unsubscribe_location_updates;
}


static void _dbus_free_smartphone_context_manager_sync_subscribe_location_updates (FreeSmartphoneContextManagerSync* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	FreeSmartphoneContextLocationUpdateAccuracy desired_accuracy = 0;
	GVariant* _tmp327_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp327_ = g_variant_iter_next_value (&_arguments_iter);
	desired_accuracy = free_smartphone_context_location_update_accuracy_from_string (g_variant_get_string (_tmp327_, NULL), &error);
	g_variant_unref (_tmp327_);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	free_smartphone_context_manager_sync_subscribe_location_updates (self, desired_accuracy, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_free_smartphone_context_manager_sync_unsubscribe_location_updates (FreeSmartphoneContextManagerSync* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	free_smartphone_context_manager_sync_unsubscribe_location_updates (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void free_smartphone_context_manager_sync_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "SubscribeLocationUpdates") == 0) {
		_dbus_free_smartphone_context_manager_sync_subscribe_location_updates (object, parameters, invocation);
	} else if (strcmp (method_name, "UnsubscribeLocationUpdates") == 0) {
		_dbus_free_smartphone_context_manager_sync_unsubscribe_location_updates (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* free_smartphone_context_manager_sync_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean free_smartphone_context_manager_sync_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint free_smartphone_context_manager_sync_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_free_smartphone_context_manager_sync_dbus_interface_info), &_free_smartphone_context_manager_sync_dbus_interface_vtable, data, _free_smartphone_context_manager_sync_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _free_smartphone_context_manager_sync_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


GType free_smartphone_context_location_update_accuracy_get_type (void) {
	static volatile gsize free_smartphone_context_location_update_accuracy_type_id__volatile = 0;
	if (g_once_init_enter (&free_smartphone_context_location_update_accuracy_type_id__volatile)) {
		static const GEnumValue values[] = {{FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_INVALID, "FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_INVALID", "invalid"}, {FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_NAVI, "FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_NAVI", "navi"}, {FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_BEST, "FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_BEST", "best"}, {FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_10M, "FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_10M", "10m"}, {FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100M, "FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100M", "100m"}, {FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_1KM, "FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_1KM", "1km"}, {FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_3KM, "FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_3KM", "3km"}, {FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100KM, "FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100KM", "100km"}, {0, NULL, NULL}};
		GType free_smartphone_context_location_update_accuracy_type_id;
		free_smartphone_context_location_update_accuracy_type_id = g_enum_register_static ("FreeSmartphoneContextLocationUpdateAccuracy", values);
		g_once_init_leave (&free_smartphone_context_location_update_accuracy_type_id__volatile, free_smartphone_context_location_update_accuracy_type_id);
	}
	return free_smartphone_context_location_update_accuracy_type_id__volatile;
}


FreeSmartphoneContextLocationUpdateAccuracy free_smartphone_context_location_update_accuracy_from_string (const char* str, GError** error) {
	FreeSmartphoneContextLocationUpdateAccuracy value = 0;
	if (strcmp (str, "invalid") == 0) {
		value = FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_INVALID;
	} else if (strcmp (str, "navigation") == 0) {
		value = FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_NAVI;
	} else if (strcmp (str, "best") == 0) {
		value = FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_BEST;
	} else if (strcmp (str, "nearest-ten-meters") == 0) {
		value = FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_10M;
	} else if (strcmp (str, "hundred-meters") == 0) {
		value = FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100M;
	} else if (strcmp (str, "one-kilometer") == 0) {
		value = FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_1KM;
	} else if (strcmp (str, "three-kilometers") == 0) {
		value = FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_3KM;
	} else if (strcmp (str, "hundred-kilometers") == 0) {
		value = FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100KM;
	} else {
		g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "Invalid value for enum `FreeSmartphoneContextLocationUpdateAccuracy'");
	}
	return value;
}


const char* free_smartphone_context_location_update_accuracy_to_string (FreeSmartphoneContextLocationUpdateAccuracy value) {
	const char * str;
	switch (value) {
		case FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_INVALID:
		str = "invalid";
		break;
		case FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_NAVI:
		str = "navigation";
		break;
		case FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_BEST:
		str = "best";
		break;
		case FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_10M:
		str = "nearest-ten-meters";
		break;
		case FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100M:
		str = "hundred-meters";
		break;
		case FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_1KM:
		str = "one-kilometer";
		break;
		case FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_3KM:
		str = "three-kilometers";
		break;
		case FREE_SMARTPHONE_CONTEXT_LOCATION_UPDATE_ACCURACY_100KM:
		str = "hundred-kilometers";
		break;
	}
	return str;
}



