/* freesmartphone-time.c generated by valac 0.16.0, the Vala compiler
 * generated from freesmartphone-time.vala, do not modify */

/* Generated by vala-dbus-binding-tool 0.4.0. Do not modify! */
/* Generated with: vala-dbus-binding-tool --api-path=/usr/local/share/freesmartphone/xml --directory=../src --strip-namespace=org --rename-namespace=freedesktop:FreeDesktop --rename-namespace=freesmartphone:FreeSmartphone --gdbus */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define FREE_SMARTPHONE_TIME_TYPE_WAKEUP_ALARM (free_smartphone_time_wakeup_alarm_get_type ())
typedef struct _FreeSmartphoneTimeWakeupAlarm FreeSmartphoneTimeWakeupAlarm;
#define _g_free0(var) (var = (g_free (var), NULL))

#define FREE_SMARTPHONE_TIME_TYPE_ALARM (free_smartphone_time_alarm_get_type ())
#define FREE_SMARTPHONE_TIME_ALARM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FREE_SMARTPHONE_TIME_TYPE_ALARM, FreeSmartphoneTimeAlarm))
#define FREE_SMARTPHONE_TIME_IS_ALARM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FREE_SMARTPHONE_TIME_TYPE_ALARM))
#define FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FREE_SMARTPHONE_TIME_TYPE_ALARM, FreeSmartphoneTimeAlarmIface))

typedef struct _FreeSmartphoneTimeAlarm FreeSmartphoneTimeAlarm;
typedef struct _FreeSmartphoneTimeAlarmIface FreeSmartphoneTimeAlarmIface;

#define FREE_SMARTPHONE_TIME_TYPE_ALARM_PROXY (free_smartphone_time_alarm_proxy_get_type ())
typedef GDBusProxy FreeSmartphoneTimeAlarmProxy;
typedef GDBusProxyClass FreeSmartphoneTimeAlarmProxyClass;

#define FREE_SMARTPHONE_TIME_TYPE_ALARM_SYNC (free_smartphone_time_alarm_sync_get_type ())
#define FREE_SMARTPHONE_TIME_ALARM_SYNC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FREE_SMARTPHONE_TIME_TYPE_ALARM_SYNC, FreeSmartphoneTimeAlarmSync))
#define FREE_SMARTPHONE_TIME_IS_ALARM_SYNC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FREE_SMARTPHONE_TIME_TYPE_ALARM_SYNC))
#define FREE_SMARTPHONE_TIME_ALARM_SYNC_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FREE_SMARTPHONE_TIME_TYPE_ALARM_SYNC, FreeSmartphoneTimeAlarmSyncIface))

typedef struct _FreeSmartphoneTimeAlarmSync FreeSmartphoneTimeAlarmSync;
typedef struct _FreeSmartphoneTimeAlarmSyncIface FreeSmartphoneTimeAlarmSyncIface;

#define FREE_SMARTPHONE_TIME_TYPE_ALARM_SYNC_PROXY (free_smartphone_time_alarm_sync_proxy_get_type ())
typedef GDBusProxy FreeSmartphoneTimeAlarmSyncProxy;
typedef GDBusProxyClass FreeSmartphoneTimeAlarmSyncProxyClass;

struct _FreeSmartphoneTimeWakeupAlarm {
	gchar* busname;
	gint timestamp;
};

typedef enum  {
	FREE_SMARTPHONE_ERROR_INVALID_PARAMETER,
	FREE_SMARTPHONE_ERROR_INTERNAL_ERROR,
	FREE_SMARTPHONE_ERROR_SYSTEM_ERROR,
	FREE_SMARTPHONE_ERROR_UNSUPPORTED,
	FREE_SMARTPHONE_ERROR_UNAVAILABLE
} FreeSmartphoneError;
#define FREE_SMARTPHONE_ERROR free_smartphone_error_quark ()
struct _FreeSmartphoneTimeAlarmIface {
	GTypeInterface parent_iface;
	void (*clear_alarms) (FreeSmartphoneTimeAlarm* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*clear_alarms_finish) (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
	void (*list_alarms) (FreeSmartphoneTimeAlarm* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	FreeSmartphoneTimeWakeupAlarm* (*list_alarms_finish) (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, int* result_length1, GError** error);
	void (*remove_alarm) (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*remove_alarm_finish) (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
	void (*add_alarm) (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*add_alarm_finish) (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
};

struct _FreeSmartphoneTimeAlarmSyncIface {
	GTypeInterface parent_iface;
	void (*clear_alarms) (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, GError** error);
	FreeSmartphoneTimeWakeupAlarm* (*list_alarms) (FreeSmartphoneTimeAlarmSync* self, int* result_length1, GError** error);
	void (*remove_alarm) (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error);
	void (*add_alarm) (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error);
};



GType free_smartphone_time_wakeup_alarm_get_type (void) G_GNUC_CONST;
FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_wakeup_alarm_dup (const FreeSmartphoneTimeWakeupAlarm* self);
void free_smartphone_time_wakeup_alarm_free (FreeSmartphoneTimeWakeupAlarm* self);
void free_smartphone_time_wakeup_alarm_copy (const FreeSmartphoneTimeWakeupAlarm* self, FreeSmartphoneTimeWakeupAlarm* dest);
void free_smartphone_time_wakeup_alarm_destroy (FreeSmartphoneTimeWakeupAlarm* self);
void free_smartphone_time_wakeup_alarm_init (FreeSmartphoneTimeWakeupAlarm *self, const gchar* busname, gint timestamp);
void free_smartphone_time_wakeup_alarm_from_variant (GVariant* v, FreeSmartphoneTimeWakeupAlarm* result);
static FreeSmartphoneTimeWakeupAlarm* _variant_get8 (GVariant* value);
GType free_smartphone_time_alarm_proxy_get_type (void) G_GNUC_CONST;
guint free_smartphone_time_alarm_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GQuark free_smartphone_error_quark (void);
GType free_smartphone_time_alarm_get_type (void) G_GNUC_CONST;
void free_smartphone_time_alarm_clear_alarms (FreeSmartphoneTimeAlarm* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_);
void free_smartphone_time_alarm_clear_alarms_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
void free_smartphone_time_alarm_list_alarms (FreeSmartphoneTimeAlarm* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_alarm_list_alarms_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, int* result_length1, GError** error);
void free_smartphone_time_alarm_remove_alarm (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_);
void free_smartphone_time_alarm_remove_alarm_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
void free_smartphone_time_alarm_add_alarm (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_);
void free_smartphone_time_alarm_add_alarm_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
static void free_smartphone_time_alarm_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void _vala_g_async_ready_callback (GObject *source_object, GAsyncResult *res, void *user_data);
static void free_smartphone_time_alarm_proxy_clear_alarms_async (FreeSmartphoneTimeAlarm* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void free_smartphone_time_alarm_proxy_clear_alarms_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
static void free_smartphone_time_alarm_proxy_list_alarms_async (FreeSmartphoneTimeAlarm* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_alarm_proxy_list_alarms_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, int* result_length1, GError** error);
static void free_smartphone_time_alarm_proxy_remove_alarm_async (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void free_smartphone_time_alarm_proxy_remove_alarm_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
static void free_smartphone_time_alarm_proxy_add_alarm_async (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void free_smartphone_time_alarm_proxy_add_alarm_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error);
static void free_smartphone_time_alarm_proxy_free_smartphone_time_alarm_interface_init (FreeSmartphoneTimeAlarmIface* iface);
static void _dbus_free_smartphone_time_alarm_clear_alarms (FreeSmartphoneTimeAlarm* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_time_alarm_clear_alarms_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_);
static void _dbus_free_smartphone_time_alarm_list_alarms (FreeSmartphoneTimeAlarm* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _vala_FreeSmartphoneTimeWakeupAlarm_array_free (FreeSmartphoneTimeWakeupAlarm* array, gint array_length);
static void _dbus_free_smartphone_time_alarm_list_alarms_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_);
static void _dbus_free_smartphone_time_alarm_remove_alarm (FreeSmartphoneTimeAlarm* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_time_alarm_remove_alarm_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_);
static void _dbus_free_smartphone_time_alarm_add_alarm (FreeSmartphoneTimeAlarm* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_time_alarm_add_alarm_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_);
static void free_smartphone_time_alarm_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* free_smartphone_time_alarm_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean free_smartphone_time_alarm_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _free_smartphone_time_alarm_unregister_object (gpointer user_data);
GType free_smartphone_time_alarm_sync_proxy_get_type (void) G_GNUC_CONST;
guint free_smartphone_time_alarm_sync_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType free_smartphone_time_alarm_sync_get_type (void) G_GNUC_CONST;
void free_smartphone_time_alarm_sync_clear_alarms (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, GError** error);
FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_alarm_sync_list_alarms (FreeSmartphoneTimeAlarmSync* self, int* result_length1, GError** error);
void free_smartphone_time_alarm_sync_remove_alarm (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error);
void free_smartphone_time_alarm_sync_add_alarm (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error);
static void free_smartphone_time_alarm_sync_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void free_smartphone_time_alarm_sync_proxy_clear_alarms (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, GError** error);
static FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_alarm_sync_proxy_list_alarms (FreeSmartphoneTimeAlarmSync* self, int* result_length1, GError** error);
static void free_smartphone_time_alarm_sync_proxy_remove_alarm (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error);
static void free_smartphone_time_alarm_sync_proxy_add_alarm (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error);
static void free_smartphone_time_alarm_sync_proxy_free_smartphone_time_alarm_sync_interface_init (FreeSmartphoneTimeAlarmSyncIface* iface);
static void _dbus_free_smartphone_time_alarm_sync_clear_alarms (FreeSmartphoneTimeAlarmSync* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_time_alarm_sync_list_alarms (FreeSmartphoneTimeAlarmSync* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_time_alarm_sync_remove_alarm (FreeSmartphoneTimeAlarmSync* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_free_smartphone_time_alarm_sync_add_alarm (FreeSmartphoneTimeAlarmSync* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void free_smartphone_time_alarm_sync_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* free_smartphone_time_alarm_sync_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean free_smartphone_time_alarm_sync_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _free_smartphone_time_alarm_sync_unregister_object (gpointer user_data);

static const GDBusArgInfo _free_smartphone_time_alarm_dbus_arg_info_clear_alarms_busname = {-1, "busname", "s"};
static const GDBusArgInfo * const _free_smartphone_time_alarm_dbus_arg_info_clear_alarms_in[] = {&_free_smartphone_time_alarm_dbus_arg_info_clear_alarms_busname, NULL};
static const GDBusArgInfo * const _free_smartphone_time_alarm_dbus_arg_info_clear_alarms_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_time_alarm_dbus_method_info_clear_alarms = {-1, "ClearAlarms", (GDBusArgInfo **) (&_free_smartphone_time_alarm_dbus_arg_info_clear_alarms_in), (GDBusArgInfo **) (&_free_smartphone_time_alarm_dbus_arg_info_clear_alarms_out)};
static const GDBusArgInfo _free_smartphone_time_alarm_dbus_arg_info_list_alarms_result = {-1, "result", "a(si)"};
static const GDBusArgInfo * const _free_smartphone_time_alarm_dbus_arg_info_list_alarms_in[] = {NULL};
static const GDBusArgInfo * const _free_smartphone_time_alarm_dbus_arg_info_list_alarms_out[] = {&_free_smartphone_time_alarm_dbus_arg_info_list_alarms_result, NULL};
static const GDBusMethodInfo _free_smartphone_time_alarm_dbus_method_info_list_alarms = {-1, "ListAlarms", (GDBusArgInfo **) (&_free_smartphone_time_alarm_dbus_arg_info_list_alarms_in), (GDBusArgInfo **) (&_free_smartphone_time_alarm_dbus_arg_info_list_alarms_out)};
static const GDBusArgInfo _free_smartphone_time_alarm_dbus_arg_info_remove_alarm_busname = {-1, "busname", "s"};
static const GDBusArgInfo _free_smartphone_time_alarm_dbus_arg_info_remove_alarm_timestamp = {-1, "timestamp", "i"};
static const GDBusArgInfo * const _free_smartphone_time_alarm_dbus_arg_info_remove_alarm_in[] = {&_free_smartphone_time_alarm_dbus_arg_info_remove_alarm_busname, &_free_smartphone_time_alarm_dbus_arg_info_remove_alarm_timestamp, NULL};
static const GDBusArgInfo * const _free_smartphone_time_alarm_dbus_arg_info_remove_alarm_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_time_alarm_dbus_method_info_remove_alarm = {-1, "RemoveAlarm", (GDBusArgInfo **) (&_free_smartphone_time_alarm_dbus_arg_info_remove_alarm_in), (GDBusArgInfo **) (&_free_smartphone_time_alarm_dbus_arg_info_remove_alarm_out)};
static const GDBusArgInfo _free_smartphone_time_alarm_dbus_arg_info_add_alarm_busname = {-1, "busname", "s"};
static const GDBusArgInfo _free_smartphone_time_alarm_dbus_arg_info_add_alarm_timestamp = {-1, "timestamp", "i"};
static const GDBusArgInfo * const _free_smartphone_time_alarm_dbus_arg_info_add_alarm_in[] = {&_free_smartphone_time_alarm_dbus_arg_info_add_alarm_busname, &_free_smartphone_time_alarm_dbus_arg_info_add_alarm_timestamp, NULL};
static const GDBusArgInfo * const _free_smartphone_time_alarm_dbus_arg_info_add_alarm_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_time_alarm_dbus_method_info_add_alarm = {-1, "AddAlarm", (GDBusArgInfo **) (&_free_smartphone_time_alarm_dbus_arg_info_add_alarm_in), (GDBusArgInfo **) (&_free_smartphone_time_alarm_dbus_arg_info_add_alarm_out)};
static const GDBusMethodInfo * const _free_smartphone_time_alarm_dbus_method_info[] = {&_free_smartphone_time_alarm_dbus_method_info_clear_alarms, &_free_smartphone_time_alarm_dbus_method_info_list_alarms, &_free_smartphone_time_alarm_dbus_method_info_remove_alarm, &_free_smartphone_time_alarm_dbus_method_info_add_alarm, NULL};
static const GDBusSignalInfo * const _free_smartphone_time_alarm_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _free_smartphone_time_alarm_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _free_smartphone_time_alarm_dbus_interface_info = {-1, "org.freesmartphone.Time.Alarm", (GDBusMethodInfo **) (&_free_smartphone_time_alarm_dbus_method_info), (GDBusSignalInfo **) (&_free_smartphone_time_alarm_dbus_signal_info), (GDBusPropertyInfo **) (&_free_smartphone_time_alarm_dbus_property_info)};
static const GDBusInterfaceVTable _free_smartphone_time_alarm_dbus_interface_vtable = {free_smartphone_time_alarm_dbus_interface_method_call, free_smartphone_time_alarm_dbus_interface_get_property, free_smartphone_time_alarm_dbus_interface_set_property};
static const GDBusArgInfo _free_smartphone_time_alarm_sync_dbus_arg_info_clear_alarms_busname = {-1, "busname", "s"};
static const GDBusArgInfo * const _free_smartphone_time_alarm_sync_dbus_arg_info_clear_alarms_in[] = {&_free_smartphone_time_alarm_sync_dbus_arg_info_clear_alarms_busname, NULL};
static const GDBusArgInfo * const _free_smartphone_time_alarm_sync_dbus_arg_info_clear_alarms_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_time_alarm_sync_dbus_method_info_clear_alarms = {-1, "ClearAlarms", (GDBusArgInfo **) (&_free_smartphone_time_alarm_sync_dbus_arg_info_clear_alarms_in), (GDBusArgInfo **) (&_free_smartphone_time_alarm_sync_dbus_arg_info_clear_alarms_out)};
static const GDBusArgInfo _free_smartphone_time_alarm_sync_dbus_arg_info_list_alarms_result = {-1, "result", "a(si)"};
static const GDBusArgInfo * const _free_smartphone_time_alarm_sync_dbus_arg_info_list_alarms_in[] = {NULL};
static const GDBusArgInfo * const _free_smartphone_time_alarm_sync_dbus_arg_info_list_alarms_out[] = {&_free_smartphone_time_alarm_sync_dbus_arg_info_list_alarms_result, NULL};
static const GDBusMethodInfo _free_smartphone_time_alarm_sync_dbus_method_info_list_alarms = {-1, "ListAlarms", (GDBusArgInfo **) (&_free_smartphone_time_alarm_sync_dbus_arg_info_list_alarms_in), (GDBusArgInfo **) (&_free_smartphone_time_alarm_sync_dbus_arg_info_list_alarms_out)};
static const GDBusArgInfo _free_smartphone_time_alarm_sync_dbus_arg_info_remove_alarm_busname = {-1, "busname", "s"};
static const GDBusArgInfo _free_smartphone_time_alarm_sync_dbus_arg_info_remove_alarm_timestamp = {-1, "timestamp", "i"};
static const GDBusArgInfo * const _free_smartphone_time_alarm_sync_dbus_arg_info_remove_alarm_in[] = {&_free_smartphone_time_alarm_sync_dbus_arg_info_remove_alarm_busname, &_free_smartphone_time_alarm_sync_dbus_arg_info_remove_alarm_timestamp, NULL};
static const GDBusArgInfo * const _free_smartphone_time_alarm_sync_dbus_arg_info_remove_alarm_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_time_alarm_sync_dbus_method_info_remove_alarm = {-1, "RemoveAlarm", (GDBusArgInfo **) (&_free_smartphone_time_alarm_sync_dbus_arg_info_remove_alarm_in), (GDBusArgInfo **) (&_free_smartphone_time_alarm_sync_dbus_arg_info_remove_alarm_out)};
static const GDBusArgInfo _free_smartphone_time_alarm_sync_dbus_arg_info_add_alarm_busname = {-1, "busname", "s"};
static const GDBusArgInfo _free_smartphone_time_alarm_sync_dbus_arg_info_add_alarm_timestamp = {-1, "timestamp", "i"};
static const GDBusArgInfo * const _free_smartphone_time_alarm_sync_dbus_arg_info_add_alarm_in[] = {&_free_smartphone_time_alarm_sync_dbus_arg_info_add_alarm_busname, &_free_smartphone_time_alarm_sync_dbus_arg_info_add_alarm_timestamp, NULL};
static const GDBusArgInfo * const _free_smartphone_time_alarm_sync_dbus_arg_info_add_alarm_out[] = {NULL};
static const GDBusMethodInfo _free_smartphone_time_alarm_sync_dbus_method_info_add_alarm = {-1, "AddAlarm", (GDBusArgInfo **) (&_free_smartphone_time_alarm_sync_dbus_arg_info_add_alarm_in), (GDBusArgInfo **) (&_free_smartphone_time_alarm_sync_dbus_arg_info_add_alarm_out)};
static const GDBusMethodInfo * const _free_smartphone_time_alarm_sync_dbus_method_info[] = {&_free_smartphone_time_alarm_sync_dbus_method_info_clear_alarms, &_free_smartphone_time_alarm_sync_dbus_method_info_list_alarms, &_free_smartphone_time_alarm_sync_dbus_method_info_remove_alarm, &_free_smartphone_time_alarm_sync_dbus_method_info_add_alarm, NULL};
static const GDBusSignalInfo * const _free_smartphone_time_alarm_sync_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _free_smartphone_time_alarm_sync_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _free_smartphone_time_alarm_sync_dbus_interface_info = {-1, "org.freesmartphone.Time.Alarm", (GDBusMethodInfo **) (&_free_smartphone_time_alarm_sync_dbus_method_info), (GDBusSignalInfo **) (&_free_smartphone_time_alarm_sync_dbus_signal_info), (GDBusPropertyInfo **) (&_free_smartphone_time_alarm_sync_dbus_property_info)};
static const GDBusInterfaceVTable _free_smartphone_time_alarm_sync_dbus_interface_vtable = {free_smartphone_time_alarm_sync_dbus_interface_method_call, free_smartphone_time_alarm_sync_dbus_interface_get_property, free_smartphone_time_alarm_sync_dbus_interface_set_property};

void free_smartphone_time_wakeup_alarm_init (FreeSmartphoneTimeWakeupAlarm *self, const gchar* busname, gint timestamp) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gint _tmp2_;
	g_return_if_fail (busname != NULL);
	memset (self, 0, sizeof (FreeSmartphoneTimeWakeupAlarm));
	_tmp0_ = busname;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*self).busname);
	(*self).busname = _tmp1_;
	_tmp2_ = timestamp;
	(*self).timestamp = _tmp2_;
}


static FreeSmartphoneTimeWakeupAlarm* _variant_get8 (GVariant* value) {
	FreeSmartphoneTimeWakeupAlarm _tmp2_;
	GVariantIter _tmp3_;
	GVariant* _tmp4_;
	GVariant* _tmp5_;
	g_variant_iter_init (&_tmp3_, value);
	_tmp4_ = g_variant_iter_next_value (&_tmp3_);
	_tmp2_.busname = g_variant_dup_string (_tmp4_, NULL);
	g_variant_unref (_tmp4_);
	_tmp5_ = g_variant_iter_next_value (&_tmp3_);
	_tmp2_.timestamp = g_variant_get_int32 (_tmp5_);
	g_variant_unref (_tmp5_);
	return g_memdup (&_tmp2_, sizeof (FreeSmartphoneTimeWakeupAlarm));
}


void free_smartphone_time_wakeup_alarm_from_variant (GVariant* v, FreeSmartphoneTimeWakeupAlarm* result) {
	GVariant* _tmp0_;
	FreeSmartphoneTimeWakeupAlarm* _tmp1_;
	FreeSmartphoneTimeWakeupAlarm _tmp6_ = {0};
	g_return_if_fail (v != NULL);
	_tmp0_ = v;
	_tmp1_ = _variant_get8 (_tmp0_);
	free_smartphone_time_wakeup_alarm_copy (_tmp1_, &_tmp6_);
	*result = _tmp6_;
	return;
}


void free_smartphone_time_wakeup_alarm_copy (const FreeSmartphoneTimeWakeupAlarm* self, FreeSmartphoneTimeWakeupAlarm* dest) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gint _tmp2_;
	_tmp0_ = (*self).busname;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).busname);
	(*dest).busname = _tmp1_;
	_tmp2_ = (*self).timestamp;
	(*dest).timestamp = _tmp2_;
}


void free_smartphone_time_wakeup_alarm_destroy (FreeSmartphoneTimeWakeupAlarm* self) {
	_g_free0 ((*self).busname);
}


FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_wakeup_alarm_dup (const FreeSmartphoneTimeWakeupAlarm* self) {
	FreeSmartphoneTimeWakeupAlarm* dup;
	dup = g_new0 (FreeSmartphoneTimeWakeupAlarm, 1);
	free_smartphone_time_wakeup_alarm_copy (self, dup);
	return dup;
}


void free_smartphone_time_wakeup_alarm_free (FreeSmartphoneTimeWakeupAlarm* self) {
	free_smartphone_time_wakeup_alarm_destroy (self);
	g_free (self);
}


GType free_smartphone_time_wakeup_alarm_get_type (void) {
	static volatile gsize free_smartphone_time_wakeup_alarm_type_id__volatile = 0;
	if (g_once_init_enter (&free_smartphone_time_wakeup_alarm_type_id__volatile)) {
		GType free_smartphone_time_wakeup_alarm_type_id;
		free_smartphone_time_wakeup_alarm_type_id = g_boxed_type_register_static ("FreeSmartphoneTimeWakeupAlarm", (GBoxedCopyFunc) free_smartphone_time_wakeup_alarm_dup, (GBoxedFreeFunc) free_smartphone_time_wakeup_alarm_free);
		g_once_init_leave (&free_smartphone_time_wakeup_alarm_type_id__volatile, free_smartphone_time_wakeup_alarm_type_id);
	}
	return free_smartphone_time_wakeup_alarm_type_id__volatile;
}


void free_smartphone_time_alarm_clear_alarms (FreeSmartphoneTimeAlarm* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE (self)->clear_alarms (self, busname, _callback_, _user_data_);
}


void free_smartphone_time_alarm_clear_alarms_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error) {
	FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE (self)->clear_alarms_finish (self, _res_, error);
}


void free_smartphone_time_alarm_list_alarms (FreeSmartphoneTimeAlarm* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE (self)->list_alarms (self, _callback_, _user_data_);
}


FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_alarm_list_alarms_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, int* result_length1, GError** error) {
	return FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE (self)->list_alarms_finish (self, _res_, result_length1, error);
}


void free_smartphone_time_alarm_remove_alarm (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE (self)->remove_alarm (self, busname, timestamp, _callback_, _user_data_);
}


void free_smartphone_time_alarm_remove_alarm_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error) {
	FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE (self)->remove_alarm_finish (self, _res_, error);
}


void free_smartphone_time_alarm_add_alarm (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE (self)->add_alarm (self, busname, timestamp, _callback_, _user_data_);
}


void free_smartphone_time_alarm_add_alarm_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error) {
	FREE_SMARTPHONE_TIME_ALARM_GET_INTERFACE (self)->add_alarm_finish (self, _res_, error);
}


static void free_smartphone_time_alarm_base_init (FreeSmartphoneTimeAlarmIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType free_smartphone_time_alarm_get_type (void) {
	static volatile gsize free_smartphone_time_alarm_type_id__volatile = 0;
	if (g_once_init_enter (&free_smartphone_time_alarm_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FreeSmartphoneTimeAlarmIface), (GBaseInitFunc) free_smartphone_time_alarm_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType free_smartphone_time_alarm_type_id;
		free_smartphone_time_alarm_type_id = g_type_register_static (G_TYPE_INTERFACE, "FreeSmartphoneTimeAlarm", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (free_smartphone_time_alarm_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (free_smartphone_time_alarm_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) free_smartphone_time_alarm_proxy_get_type);
		g_type_set_qdata (free_smartphone_time_alarm_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freesmartphone.Time.Alarm");
		g_type_set_qdata (free_smartphone_time_alarm_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) free_smartphone_time_alarm_register_object);
		g_once_init_leave (&free_smartphone_time_alarm_type_id__volatile, free_smartphone_time_alarm_type_id);
	}
	return free_smartphone_time_alarm_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (FreeSmartphoneTimeAlarmProxy, free_smartphone_time_alarm_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (FREE_SMARTPHONE_TIME_TYPE_ALARM, free_smartphone_time_alarm_proxy_free_smartphone_time_alarm_interface_init) )
static void free_smartphone_time_alarm_proxy_class_init (FreeSmartphoneTimeAlarmProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = free_smartphone_time_alarm_proxy_g_signal;
}


static void free_smartphone_time_alarm_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void free_smartphone_time_alarm_proxy_init (FreeSmartphoneTimeAlarmProxy* self) {
}


static void _vala_g_async_ready_callback (GObject *source_object, GAsyncResult *res, void *user_data) {
	g_simple_async_result_set_op_res_gpointer (user_data, g_object_ref (res), g_object_unref);
	g_simple_async_result_complete (user_data);
	g_object_unref (user_data);
}


static void free_smartphone_time_alarm_proxy_clear_alarms_async (FreeSmartphoneTimeAlarm* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Time.Alarm", "ClearAlarms");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (busname));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	g_dbus_connection_send_message_with_reply (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, _vala_g_async_ready_callback, g_simple_async_result_new ((GObject *) self, _callback_, _user_data_, NULL));
	g_object_unref (_message);
}


static void free_smartphone_time_alarm_proxy_clear_alarms_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error) {
	GDBusMessage *_reply_message;
	_reply_message = g_dbus_connection_send_message_with_reply_finish (g_dbus_proxy_get_connection ((GDBusProxy *) self), g_simple_async_result_get_op_res_gpointer ((GSimpleAsyncResult *) _res_), error);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_time_alarm_proxy_list_alarms_async (FreeSmartphoneTimeAlarm* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Time.Alarm", "ListAlarms");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	g_dbus_connection_send_message_with_reply (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, _vala_g_async_ready_callback, g_simple_async_result_new ((GObject *) self, _callback_, _user_data_, NULL));
	g_object_unref (_message);
}


static FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_alarm_proxy_list_alarms_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, int* result_length1, GError** error) {
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	FreeSmartphoneTimeWakeupAlarm* _result;
	int _result_length1;
	GVariant* _tmp1424_;
	FreeSmartphoneTimeWakeupAlarm* _tmp1425_;
	int _tmp1425__length;
	int _tmp1425__size;
	int _tmp1425__length1;
	GVariantIter _tmp1426_;
	GVariant* _tmp1427_;
	_reply_message = g_dbus_connection_send_message_with_reply_finish (g_dbus_proxy_get_connection ((GDBusProxy *) self), g_simple_async_result_get_op_res_gpointer ((GSimpleAsyncResult *) _res_), error);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_result_length1 = 0;
	_tmp1424_ = g_variant_iter_next_value (&_reply_iter);
	_tmp1425_ = g_new (FreeSmartphoneTimeWakeupAlarm, 5);
	_tmp1425__length = 0;
	_tmp1425__size = 4;
	_tmp1425__length1 = 0;
	g_variant_iter_init (&_tmp1426_, _tmp1424_);
	for (; (_tmp1427_ = g_variant_iter_next_value (&_tmp1426_)) != NULL; _tmp1425__length1++) {
		FreeSmartphoneTimeWakeupAlarm _tmp1428_;
		GVariantIter _tmp1429_;
		GVariant* _tmp1430_;
		GVariant* _tmp1431_;
		if (_tmp1425__size == _tmp1425__length) {
			_tmp1425__size = 2 * _tmp1425__size;
			_tmp1425_ = g_renew (FreeSmartphoneTimeWakeupAlarm, _tmp1425_, _tmp1425__size + 1);
		}
		g_variant_iter_init (&_tmp1429_, _tmp1427_);
		_tmp1430_ = g_variant_iter_next_value (&_tmp1429_);
		_tmp1428_.busname = g_variant_dup_string (_tmp1430_, NULL);
		g_variant_unref (_tmp1430_);
		_tmp1431_ = g_variant_iter_next_value (&_tmp1429_);
		_tmp1428_.timestamp = g_variant_get_int32 (_tmp1431_);
		g_variant_unref (_tmp1431_);
		_tmp1425_[_tmp1425__length++] = _tmp1428_;
		g_variant_unref (_tmp1427_);
	}
	_result_length1 = _tmp1425__length1;
	_result = _tmp1425_;
	g_variant_unref (_tmp1424_);
	*result_length1 = _result_length1;
	g_object_unref (_reply_message);
	return _result;
}


static void free_smartphone_time_alarm_proxy_remove_alarm_async (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Time.Alarm", "RemoveAlarm");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (busname));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (timestamp));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	g_dbus_connection_send_message_with_reply (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, _vala_g_async_ready_callback, g_simple_async_result_new ((GObject *) self, _callback_, _user_data_, NULL));
	g_object_unref (_message);
}


static void free_smartphone_time_alarm_proxy_remove_alarm_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error) {
	GDBusMessage *_reply_message;
	_reply_message = g_dbus_connection_send_message_with_reply_finish (g_dbus_proxy_get_connection ((GDBusProxy *) self), g_simple_async_result_get_op_res_gpointer ((GSimpleAsyncResult *) _res_), error);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_time_alarm_proxy_add_alarm_async (FreeSmartphoneTimeAlarm* self, const gchar* busname, gint timestamp, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	FREE_SMARTPHONE_ERROR;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Time.Alarm", "AddAlarm");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (busname));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (timestamp));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	g_dbus_connection_send_message_with_reply (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, _vala_g_async_ready_callback, g_simple_async_result_new ((GObject *) self, _callback_, _user_data_, NULL));
	g_object_unref (_message);
}


static void free_smartphone_time_alarm_proxy_add_alarm_finish (FreeSmartphoneTimeAlarm* self, GAsyncResult* _res_, GError** error) {
	GDBusMessage *_reply_message;
	_reply_message = g_dbus_connection_send_message_with_reply_finish (g_dbus_proxy_get_connection ((GDBusProxy *) self), g_simple_async_result_get_op_res_gpointer ((GSimpleAsyncResult *) _res_), error);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_time_alarm_proxy_free_smartphone_time_alarm_interface_init (FreeSmartphoneTimeAlarmIface* iface) {
	iface->clear_alarms = free_smartphone_time_alarm_proxy_clear_alarms_async;
	iface->clear_alarms_finish = free_smartphone_time_alarm_proxy_clear_alarms_finish;
	iface->list_alarms = free_smartphone_time_alarm_proxy_list_alarms_async;
	iface->list_alarms_finish = free_smartphone_time_alarm_proxy_list_alarms_finish;
	iface->remove_alarm = free_smartphone_time_alarm_proxy_remove_alarm_async;
	iface->remove_alarm_finish = free_smartphone_time_alarm_proxy_remove_alarm_finish;
	iface->add_alarm = free_smartphone_time_alarm_proxy_add_alarm_async;
	iface->add_alarm_finish = free_smartphone_time_alarm_proxy_add_alarm_finish;
}


static void _dbus_free_smartphone_time_alarm_clear_alarms (FreeSmartphoneTimeAlarm* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GVariantIter _arguments_iter;
	gchar* busname = NULL;
	GVariant* _tmp1432_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp1432_ = g_variant_iter_next_value (&_arguments_iter);
	busname = g_variant_dup_string (_tmp1432_, NULL);
	g_variant_unref (_tmp1432_);
	free_smartphone_time_alarm_clear_alarms (self, busname, (GAsyncReadyCallback) _dbus_free_smartphone_time_alarm_clear_alarms_ready, invocation);
	_g_free0 (busname);
}


static void _dbus_free_smartphone_time_alarm_clear_alarms_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_) {
	GDBusMethodInvocation * invocation;
	GError* error = NULL;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	invocation = _user_data_;
	free_smartphone_time_alarm_clear_alarms_finish ((FreeSmartphoneTimeAlarm*) source_object, _res_, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_free_smartphone_time_alarm_list_alarms (FreeSmartphoneTimeAlarm* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GVariantIter _arguments_iter;
	g_variant_iter_init (&_arguments_iter, parameters);
	free_smartphone_time_alarm_list_alarms (self, (GAsyncReadyCallback) _dbus_free_smartphone_time_alarm_list_alarms_ready, invocation);
}


static void _vala_FreeSmartphoneTimeWakeupAlarm_array_free (FreeSmartphoneTimeWakeupAlarm* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			free_smartphone_time_wakeup_alarm_destroy (&array[i]);
		}
	}
	g_free (array);
}


static void _dbus_free_smartphone_time_alarm_list_alarms_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_) {
	GDBusMethodInvocation * invocation;
	GError* error = NULL;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	FreeSmartphoneTimeWakeupAlarm* result;
	int result_length1 = 0;
	FreeSmartphoneTimeWakeupAlarm* _tmp1433_;
	GVariantBuilder _tmp1434_;
	int _tmp1435_;
	invocation = _user_data_;
	result = free_smartphone_time_alarm_list_alarms_finish ((FreeSmartphoneTimeAlarm*) source_object, _res_, &result_length1, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_tmp1433_ = result;
	g_variant_builder_init (&_tmp1434_, G_VARIANT_TYPE ("a(si)"));
	for (_tmp1435_ = 0; _tmp1435_ < result_length1; _tmp1435_++) {
		GVariantBuilder _tmp1436_;
		g_variant_builder_init (&_tmp1436_, G_VARIANT_TYPE_TUPLE);
		g_variant_builder_add_value (&_tmp1436_, g_variant_new_string ((*_tmp1433_).busname));
		g_variant_builder_add_value (&_tmp1436_, g_variant_new_int32 ((*_tmp1433_).timestamp));
		g_variant_builder_add_value (&_tmp1434_, g_variant_builder_end (&_tmp1436_));
		_tmp1433_++;
	}
	g_variant_builder_add_value (&_reply_builder, g_variant_builder_end (&_tmp1434_));
	result = (_vala_FreeSmartphoneTimeWakeupAlarm_array_free (result, result_length1), NULL);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_free_smartphone_time_alarm_remove_alarm (FreeSmartphoneTimeAlarm* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GVariantIter _arguments_iter;
	gchar* busname = NULL;
	GVariant* _tmp1437_;
	gint timestamp = 0;
	GVariant* _tmp1438_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp1437_ = g_variant_iter_next_value (&_arguments_iter);
	busname = g_variant_dup_string (_tmp1437_, NULL);
	g_variant_unref (_tmp1437_);
	_tmp1438_ = g_variant_iter_next_value (&_arguments_iter);
	timestamp = g_variant_get_int32 (_tmp1438_);
	g_variant_unref (_tmp1438_);
	free_smartphone_time_alarm_remove_alarm (self, busname, timestamp, (GAsyncReadyCallback) _dbus_free_smartphone_time_alarm_remove_alarm_ready, invocation);
	_g_free0 (busname);
}


static void _dbus_free_smartphone_time_alarm_remove_alarm_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_) {
	GDBusMethodInvocation * invocation;
	GError* error = NULL;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	invocation = _user_data_;
	free_smartphone_time_alarm_remove_alarm_finish ((FreeSmartphoneTimeAlarm*) source_object, _res_, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_free_smartphone_time_alarm_add_alarm (FreeSmartphoneTimeAlarm* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GVariantIter _arguments_iter;
	gchar* busname = NULL;
	GVariant* _tmp1439_;
	gint timestamp = 0;
	GVariant* _tmp1440_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp1439_ = g_variant_iter_next_value (&_arguments_iter);
	busname = g_variant_dup_string (_tmp1439_, NULL);
	g_variant_unref (_tmp1439_);
	_tmp1440_ = g_variant_iter_next_value (&_arguments_iter);
	timestamp = g_variant_get_int32 (_tmp1440_);
	g_variant_unref (_tmp1440_);
	free_smartphone_time_alarm_add_alarm (self, busname, timestamp, (GAsyncReadyCallback) _dbus_free_smartphone_time_alarm_add_alarm_ready, invocation);
	_g_free0 (busname);
}


static void _dbus_free_smartphone_time_alarm_add_alarm_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_) {
	GDBusMethodInvocation * invocation;
	GError* error = NULL;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	invocation = _user_data_;
	free_smartphone_time_alarm_add_alarm_finish ((FreeSmartphoneTimeAlarm*) source_object, _res_, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void free_smartphone_time_alarm_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "ClearAlarms") == 0) {
		_dbus_free_smartphone_time_alarm_clear_alarms (object, parameters, invocation);
	} else if (strcmp (method_name, "ListAlarms") == 0) {
		_dbus_free_smartphone_time_alarm_list_alarms (object, parameters, invocation);
	} else if (strcmp (method_name, "RemoveAlarm") == 0) {
		_dbus_free_smartphone_time_alarm_remove_alarm (object, parameters, invocation);
	} else if (strcmp (method_name, "AddAlarm") == 0) {
		_dbus_free_smartphone_time_alarm_add_alarm (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* free_smartphone_time_alarm_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean free_smartphone_time_alarm_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint free_smartphone_time_alarm_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_free_smartphone_time_alarm_dbus_interface_info), &_free_smartphone_time_alarm_dbus_interface_vtable, data, _free_smartphone_time_alarm_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _free_smartphone_time_alarm_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


void free_smartphone_time_alarm_sync_clear_alarms (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, GError** error) {
	g_return_if_fail (self != NULL);
	FREE_SMARTPHONE_TIME_ALARM_SYNC_GET_INTERFACE (self)->clear_alarms (self, busname, error);
}


FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_alarm_sync_list_alarms (FreeSmartphoneTimeAlarmSync* self, int* result_length1, GError** error) {
	g_return_val_if_fail (self != NULL, NULL);
	return FREE_SMARTPHONE_TIME_ALARM_SYNC_GET_INTERFACE (self)->list_alarms (self, result_length1, error);
}


void free_smartphone_time_alarm_sync_remove_alarm (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error) {
	g_return_if_fail (self != NULL);
	FREE_SMARTPHONE_TIME_ALARM_SYNC_GET_INTERFACE (self)->remove_alarm (self, busname, timestamp, error);
}


void free_smartphone_time_alarm_sync_add_alarm (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error) {
	g_return_if_fail (self != NULL);
	FREE_SMARTPHONE_TIME_ALARM_SYNC_GET_INTERFACE (self)->add_alarm (self, busname, timestamp, error);
}


static void free_smartphone_time_alarm_sync_base_init (FreeSmartphoneTimeAlarmSyncIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType free_smartphone_time_alarm_sync_get_type (void) {
	static volatile gsize free_smartphone_time_alarm_sync_type_id__volatile = 0;
	if (g_once_init_enter (&free_smartphone_time_alarm_sync_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FreeSmartphoneTimeAlarmSyncIface), (GBaseInitFunc) free_smartphone_time_alarm_sync_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType free_smartphone_time_alarm_sync_type_id;
		free_smartphone_time_alarm_sync_type_id = g_type_register_static (G_TYPE_INTERFACE, "FreeSmartphoneTimeAlarmSync", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (free_smartphone_time_alarm_sync_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (free_smartphone_time_alarm_sync_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) free_smartphone_time_alarm_sync_proxy_get_type);
		g_type_set_qdata (free_smartphone_time_alarm_sync_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freesmartphone.Time.Alarm");
		g_type_set_qdata (free_smartphone_time_alarm_sync_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) free_smartphone_time_alarm_sync_register_object);
		g_once_init_leave (&free_smartphone_time_alarm_sync_type_id__volatile, free_smartphone_time_alarm_sync_type_id);
	}
	return free_smartphone_time_alarm_sync_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (FreeSmartphoneTimeAlarmSyncProxy, free_smartphone_time_alarm_sync_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (FREE_SMARTPHONE_TIME_TYPE_ALARM_SYNC, free_smartphone_time_alarm_sync_proxy_free_smartphone_time_alarm_sync_interface_init) )
static void free_smartphone_time_alarm_sync_proxy_class_init (FreeSmartphoneTimeAlarmSyncProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = free_smartphone_time_alarm_sync_proxy_g_signal;
}


static void free_smartphone_time_alarm_sync_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void free_smartphone_time_alarm_sync_proxy_init (FreeSmartphoneTimeAlarmSyncProxy* self) {
}


static void free_smartphone_time_alarm_sync_proxy_clear_alarms (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Time.Alarm", "ClearAlarms");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (busname));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static FreeSmartphoneTimeWakeupAlarm* free_smartphone_time_alarm_sync_proxy_list_alarms (FreeSmartphoneTimeAlarmSync* self, int* result_length1, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	FreeSmartphoneTimeWakeupAlarm* _result;
	int _result_length1;
	GVariant* _tmp1441_;
	FreeSmartphoneTimeWakeupAlarm* _tmp1442_;
	int _tmp1442__length;
	int _tmp1442__size;
	int _tmp1442__length1;
	GVariantIter _tmp1443_;
	GVariant* _tmp1444_;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Time.Alarm", "ListAlarms");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_result_length1 = 0;
	_tmp1441_ = g_variant_iter_next_value (&_reply_iter);
	_tmp1442_ = g_new (FreeSmartphoneTimeWakeupAlarm, 5);
	_tmp1442__length = 0;
	_tmp1442__size = 4;
	_tmp1442__length1 = 0;
	g_variant_iter_init (&_tmp1443_, _tmp1441_);
	for (; (_tmp1444_ = g_variant_iter_next_value (&_tmp1443_)) != NULL; _tmp1442__length1++) {
		FreeSmartphoneTimeWakeupAlarm _tmp1445_;
		GVariantIter _tmp1446_;
		GVariant* _tmp1447_;
		GVariant* _tmp1448_;
		if (_tmp1442__size == _tmp1442__length) {
			_tmp1442__size = 2 * _tmp1442__size;
			_tmp1442_ = g_renew (FreeSmartphoneTimeWakeupAlarm, _tmp1442_, _tmp1442__size + 1);
		}
		g_variant_iter_init (&_tmp1446_, _tmp1444_);
		_tmp1447_ = g_variant_iter_next_value (&_tmp1446_);
		_tmp1445_.busname = g_variant_dup_string (_tmp1447_, NULL);
		g_variant_unref (_tmp1447_);
		_tmp1448_ = g_variant_iter_next_value (&_tmp1446_);
		_tmp1445_.timestamp = g_variant_get_int32 (_tmp1448_);
		g_variant_unref (_tmp1448_);
		_tmp1442_[_tmp1442__length++] = _tmp1445_;
		g_variant_unref (_tmp1444_);
	}
	_result_length1 = _tmp1442__length1;
	_result = _tmp1442_;
	g_variant_unref (_tmp1441_);
	*result_length1 = _result_length1;
	g_object_unref (_reply_message);
	return _result;
}


static void free_smartphone_time_alarm_sync_proxy_remove_alarm (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Time.Alarm", "RemoveAlarm");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (busname));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (timestamp));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_time_alarm_sync_proxy_add_alarm (FreeSmartphoneTimeAlarmSync* self, const gchar* busname, gint timestamp, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	FREE_SMARTPHONE_ERROR;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freesmartphone.Time.Alarm", "AddAlarm");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (busname));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (timestamp));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void free_smartphone_time_alarm_sync_proxy_free_smartphone_time_alarm_sync_interface_init (FreeSmartphoneTimeAlarmSyncIface* iface) {
	iface->clear_alarms = free_smartphone_time_alarm_sync_proxy_clear_alarms;
	iface->list_alarms = free_smartphone_time_alarm_sync_proxy_list_alarms;
	iface->remove_alarm = free_smartphone_time_alarm_sync_proxy_remove_alarm;
	iface->add_alarm = free_smartphone_time_alarm_sync_proxy_add_alarm;
}


static void _dbus_free_smartphone_time_alarm_sync_clear_alarms (FreeSmartphoneTimeAlarmSync* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* busname = NULL;
	GVariant* _tmp1449_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp1449_ = g_variant_iter_next_value (&_arguments_iter);
	busname = g_variant_dup_string (_tmp1449_, NULL);
	g_variant_unref (_tmp1449_);
	free_smartphone_time_alarm_sync_clear_alarms (self, busname, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (busname);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_free_smartphone_time_alarm_sync_list_alarms (FreeSmartphoneTimeAlarmSync* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	FreeSmartphoneTimeWakeupAlarm* result;
	int result_length1 = 0;
	FreeSmartphoneTimeWakeupAlarm* _tmp1450_;
	GVariantBuilder _tmp1451_;
	int _tmp1452_;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = free_smartphone_time_alarm_sync_list_alarms (self, &result_length1, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_tmp1450_ = result;
	g_variant_builder_init (&_tmp1451_, G_VARIANT_TYPE ("a(si)"));
	for (_tmp1452_ = 0; _tmp1452_ < result_length1; _tmp1452_++) {
		GVariantBuilder _tmp1453_;
		g_variant_builder_init (&_tmp1453_, G_VARIANT_TYPE_TUPLE);
		g_variant_builder_add_value (&_tmp1453_, g_variant_new_string ((*_tmp1450_).busname));
		g_variant_builder_add_value (&_tmp1453_, g_variant_new_int32 ((*_tmp1450_).timestamp));
		g_variant_builder_add_value (&_tmp1451_, g_variant_builder_end (&_tmp1453_));
		_tmp1450_++;
	}
	g_variant_builder_add_value (&_reply_builder, g_variant_builder_end (&_tmp1451_));
	result = (_vala_FreeSmartphoneTimeWakeupAlarm_array_free (result, result_length1), NULL);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_free_smartphone_time_alarm_sync_remove_alarm (FreeSmartphoneTimeAlarmSync* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* busname = NULL;
	GVariant* _tmp1454_;
	gint timestamp = 0;
	GVariant* _tmp1455_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp1454_ = g_variant_iter_next_value (&_arguments_iter);
	busname = g_variant_dup_string (_tmp1454_, NULL);
	g_variant_unref (_tmp1454_);
	_tmp1455_ = g_variant_iter_next_value (&_arguments_iter);
	timestamp = g_variant_get_int32 (_tmp1455_);
	g_variant_unref (_tmp1455_);
	free_smartphone_time_alarm_sync_remove_alarm (self, busname, timestamp, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (busname);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_free_smartphone_time_alarm_sync_add_alarm (FreeSmartphoneTimeAlarmSync* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* busname = NULL;
	GVariant* _tmp1456_;
	gint timestamp = 0;
	GVariant* _tmp1457_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp1456_ = g_variant_iter_next_value (&_arguments_iter);
	busname = g_variant_dup_string (_tmp1456_, NULL);
	g_variant_unref (_tmp1456_);
	_tmp1457_ = g_variant_iter_next_value (&_arguments_iter);
	timestamp = g_variant_get_int32 (_tmp1457_);
	g_variant_unref (_tmp1457_);
	free_smartphone_time_alarm_sync_add_alarm (self, busname, timestamp, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (busname);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void free_smartphone_time_alarm_sync_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "ClearAlarms") == 0) {
		_dbus_free_smartphone_time_alarm_sync_clear_alarms (object, parameters, invocation);
	} else if (strcmp (method_name, "ListAlarms") == 0) {
		_dbus_free_smartphone_time_alarm_sync_list_alarms (object, parameters, invocation);
	} else if (strcmp (method_name, "RemoveAlarm") == 0) {
		_dbus_free_smartphone_time_alarm_sync_remove_alarm (object, parameters, invocation);
	} else if (strcmp (method_name, "AddAlarm") == 0) {
		_dbus_free_smartphone_time_alarm_sync_add_alarm (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* free_smartphone_time_alarm_sync_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean free_smartphone_time_alarm_sync_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint free_smartphone_time_alarm_sync_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_free_smartphone_time_alarm_sync_dbus_interface_info), &_free_smartphone_time_alarm_sync_dbus_interface_vtable, data, _free_smartphone_time_alarm_sync_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _free_smartphone_time_alarm_sync_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}



