/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool --api-path=/usr/local/share/freesmartphone/xml --directory=./ --strip-namespace=org --rename-namespace=freedesktop:FreeDesktop --rename-namespace=freesmartphone:FreeSmartphone --gdbus */
using GLib;

namespace FreeSmartphone {

	namespace Context {

		[DBus (name = "org.freesmartphone.Context.Client", timeout = 120000)]
		public interface Client : GLib.Object {

			[DBus (name = "LocationUpdate", no_reply = true)]
			public abstract void location_update(GLib.HashTable<string, GLib.Variant> from, GLib.HashTable<string, GLib.Variant> to) throws FreeSmartphone.Error, DBusError, IOError;
		}

		[DBus (name = "org.freesmartphone.Context.Client", timeout = 120000)]
		public interface ClientSync : GLib.Object {

			[DBus (name = "LocationUpdate", no_reply = true)]
			public abstract void location_update(GLib.HashTable<string, GLib.Variant> from, GLib.HashTable<string, GLib.Variant> to) throws FreeSmartphone.Error, DBusError, IOError;
		}

		[DBus (name = "org.freesmartphone.Context.Manager", timeout = 120000)]
		public interface Manager : GLib.Object {

			[DBus (name = "SubscribeLocationUpdates")]
			public abstract async void subscribe_location_updates(FreeSmartphone.Context.LocationUpdateAccuracy desired_accuracy) throws FreeSmartphone.Error, DBusError, IOError;

			[DBus (name = "UnsubscribeLocationUpdates")]
			public abstract async void unsubscribe_location_updates() throws FreeSmartphone.Error, DBusError, IOError;
		}

		[DBus (name = "org.freesmartphone.Context.Manager", timeout = 120000)]
		public interface ManagerSync : GLib.Object {

			[DBus (name = "SubscribeLocationUpdates")]
			public abstract void subscribe_location_updates(FreeSmartphone.Context.LocationUpdateAccuracy desired_accuracy) throws FreeSmartphone.Error, DBusError, IOError;

			[DBus (name = "UnsubscribeLocationUpdates")]
			public abstract void unsubscribe_location_updates() throws FreeSmartphone.Error, DBusError, IOError;
		}

		[DBus (use_string_marshalling = true)]
		public enum LocationUpdateAccuracy {
			[DBus (value="invalid")]
			INVALID,
			[DBus (value="navigation")]
			NAVI,
			[DBus (value="best")]
			BEST,
			[DBus (value="nearest-ten-meters")]
			10M,
			[DBus (value="hundred-meters")]
			100M,
			[DBus (value="one-kilometer")]
			1KM,
			[DBus (value="three-kilometers")]
			3KM,
			[DBus (value="hundred-kilometers")]
			100KM,
		}
	}
}
